# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  Jucsin的技术博客
email: 1033784992@qq.com
description: > # this means to ignore newlines until "baseurl:"
  <p>You are waiting for a train</p>
  <p>a train that will take you far away</p> 
  <p>You know where you hope this train will take you</p>
  <p>but you can't be sure</p>
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jucsinyu.com" # the base hostname & protocol for your site
twitter_username: DurianSUN
github_username:  DurianSUN
encoding: utf-8
kramdown:
  input: GFM
# Build settings
markdown: kramdown
paginate: 1
