# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jucsin'home
email: 1033784992@qq.com
description: > # this means to ignore newlines until "baseurl:"
  <p>清晨入古寺，初日照高林。</p>
  <p>曲径通幽处，禅房花木深. </p>
  <p>山光悦鸟性，潭影空人心. </p>
  <p>万籁此俱寂，惟闻钟磬音。</p>
  
baseurl: "http://jucsinyu.com" # the subpath of your site, e.g. /blog
url: "http://jucsinyu.com" # the base hostname & protocol for your site
twitter_username: DurianSUN
github_username:  DurianSUN
encoding: utf-8

# Build settings
markdown: kramdown
